=== INCATools/dead_simple_owl_design_patterns/src/attic/spec/DOSDP_schema_full.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "additionalProperties": false,
    "definitions": {
        "annotations": {
            "oneOf": [
                {
                    "$ref": "#/definitions/printf_annotation"
                },
                {
                    "$ref": "#/definitions/list_annotation"
                }
            ]
        },
        "list_annotation": {
            "additionalProperties": false,
            "properties": {
                "annotationProperty": {
                    "description": "A string corresponding to the rdfs:label of an owl annotation property. If the annotation property has no label, the shortForm ID should be used. The annotation property must be listed in the annotation property dictionary.'\n",
                    "type": "string"
                },
                "value": {
                    "description": "A single list variable (list_var or data_list_var).  Each item in this list  should be used to generate a separate annotation axiom.\n",
                    "type": "string"
                }
            },
            "required": [
                "annotationProperty",
                "value"
            ],
            "type": "object"
        },
        "list_annotation_obo": {
            "additionalProperties": false,
            "properties": {
                "value": {
                    "description": "A single list variable (list_var or data_list_var).  Each item in this list  should be used to generate a separate annotation axiom.\n",
                    "type": "string"
                },
                "xrefs": {
                    "description": "Takes the name of a single data_list_var specifying a list of database  cross references. Use of this field should add the same xref set to all  annotation axioms generated.\n",
                    "mapping": "oboInOwl:hasDbXref",
                    "type": "string"
                }
            },
            "required": [
                "value"
            ],
            "type": "object"
        },
        "opa": {
            "additionalProperties": false,
            "properties": {
                "annotations": {
                    "items": {
                        "$ref": "#/definitions/annotations"
                    },
                    "type": "array"
                },
                "edge": {
                    "description": "A triple specified as an ordered array with 3 elements [subject, rel, object] * rel must be the quoted name of a relation from the relations (object property) dictionary. * subject and object must be the name of an individual specified in the nodes field.\n",
                    "items": {
                        "type": "string"
                    },
                    "maxItems": 3,
                    "minItems": 3,
                    "type": "array"
                },
                "not": {
                    "description": "Optional field for negated OPAs",
                    "type": "boolean"
                }
            },
            "required": [
                "edge"
            ],
            "type": "object"
        },
        "printf_annotation": {
            "additionalProperties": false,
            "properties": {
                "annotationProperty": {
                    "description": "A string corresponding to the rdfs:label of an owl annotation property. If the annotation property has no label, the shortForm ID should be used. The annotation property must be listed in the annotation property dictionary.'\n",
                    "type": "string"
                },
                "annotations": {
                    "items": {
                        "$ref": "#/definitions/annotations"
                    },
                    "type": "array"
                },
                "text": {
                    "description": "A print format string.",
                    "type": "string"
                },
                "vars": {
                    "description": "An ordered list of variables for substitution into the accompanying print format string. Each entry must correspond to the name of a variable specified in either the 'vars' field or the data_var field of the pattern. Where an OWL entity is specified, the label for the OWL entity should be used in the substitution.  An empty var list can be specified simply by leaving this field out.\n",
                    "items": {
                        "type": "string"
                    },
                    "type": "array"
                }
            },
            "required": [
                "annotationProperty",
                "text"
            ],
            "type": "object"
        },
        "printf_annotation_obo": {
            "additionalProperties": false,
            "properties": {
                "annotations": {
                    "items": {
                        "$ref": "#/definitions/annotations"
                    },
                    "type": "array"
                },
                "text": {
                    "description": "A print format string.",
                    "type": "string"
                },
                "vars": {
                    "description": "An ordered list of variables for substitution into the accompanying print format string. Each entry must correspond to the name of a variable specified in either the 'vars' field or the data_var field of the pattern. Where an OWL entity is specified, the label for the OWL entity should be used in the substitution.\n",
                    "items": {
                        "type": "string"
                    },
                    "type": "array"
                },
                "xrefs": {
                    "description": "Takes the name of a single data_list_var specifying a list of database  cross references.\n",
                    "mapping": "oboInOwl:hasDbXref",
                    "type": "string"
                }
            },
            "required": [
                "text",
                "vars"
            ],
            "type": "object"
        },
        "printf_owl": {
            "additionalProperties": false,
            "properties": {
                "annotations": {
                    "items": {
                        "$ref": "#/definitions/annotations"
                    },
                    "type": "array"
                },
                "axiom_type": {
                    "description": "OWL axiom type expressed as manchester syntax: equivalentTo, subClassOf, disjointWith. GCI  - for general class inclusion axioms, is also valid (although missing from manchester syntax.) This specifies the axiom type to be generated from the text following substitution.'\n",
                    "enum": [
                        "equivalentTo",
                        "subClassOf",
                        "disjointWith",
                        "GCI"
                    ],
                    "type": "string"
                },
                "text": {
                    "description": "A print format string in OWL Manchester syntax. Each entry must correspond to an entry in o the name of a var in the var field of the pattern. Entries in single quotes must correspond to the labels of entries in owl_entity dictionaries (classes, relations, dataProperties)    \n",
                    "type": "string"
                },
                "vars": {
                    "description": "An ordered list of variables for substitution into the accompanying print format string. Each entry must correspond to the name of a variable specified in either the 'vars' field or the data_var field of the pattern.   An empty var list can be specified simply by leaving this field out.\n",
                    "items": {
                        "type": "string"
                    },
                    "type": "array"
                }
            },
            "required": [
                "axiom_type",
                "text",
                "vars"
            ],
            "type": "object"
        },
        "printf_owl_convenience": {
            "additionalProperties": false,
            "properties": {
                "annotations": {
                    "items": {
                        "$ref": "#/definitions/annotations"
                    },
                    "type": "array"
                },
                "text": {
                    "description": "A print format string in OWL Manchester syntax. Each entry must correspond to an entry in o the name of a var in the var field of the pattern. Entries in single quotes must correspond to the labels of entries in owl_entity dictionaries (classes, relations, dataProperties)\n",
                    "type": "string"
                },
                "vars": {
                    "description": "An ordered list of variables for substitution into the accompanying print format string. Each entry must correspond to the name of a variable\n specified in either the 'vars' field or the data_var field of the pattern.\n",
                    "items": {
                        "type": "string"
                    },
                    "type": "array"
                }
            },
            "required": [
                "text",
                "vars"
            ],
            "type": "object"
        },
        "regex_sub": {
            "additionalProperties": false,
            "properties": {
                "in": {
                    "description": "name of input var",
                    "type": "string"
                },
                "match": {
                    "description": "perl style regex match",
                    "type": "string"
                },
                "out": {
                    "description": "Name of output var.  If input var specified an OWL entity then  readable identifier is used as input to substitution\n",
                    "type": "string"
                },
                "sub": {
                    "description": "perl style regex sub.  May include backreferences.",
                    "type": "string"
                }
            },
            "required": [
                "in",
                "out",
                "match",
                "sub"
            ],
            "type": "object"
        }
    },
    "properties": {
        "GCI": {
            "$ref": "#/definitions/printf_owl_convenience"
        },
        "annotationProperties": {
            "description": "A dictionary of OWL annotation properties key : label; value : short form id",
            "type": "object"
        },
        "annotations": {
            "items": {
                "$ref": "#/definitions/printf_annotation"
            },
            "type": "array"
        },
        "base_IRI": {
            "description": "Specifies the base IRI to be used to generate new classes.",
            "type": "string"
        },
        "broad_synonym": {
            "$ref": "#/definitions/list_annotation_obo",
            "mapping": "oboInOwl:hasBroadSynonym"
        },
        "classes": {
            "description": "A dictionary of OWL classes. key :label; value : short form id",
            "type": "object"
        },
        "comment": {
            "$ref": "#/definitions/printf_annotation_obo",
            "mapping": "rdfs:comment"
        },
        "dataProperties": {
            "description": "A dictionary of OWL data properties key : label; value : short form id",
            "type": "object"
        },
        "data_list_vars": {
            "description": "A dictionary of variables rrefering to lists of some specified OWL data-types. Key = variable name, value = variable range of all items in list,  specified as a valid OWL data-type.\n"
        },
        "data_vars": {
            "description": "A dictionary of variables ranging over OWL data-types. Key = variable name, value = variable range specified as a valid OWL data-type.\n",
            "type": "object"
        },
        "def": {
            "$ref": "#/definitions/printf_annotation_obo",
            "mapping": "obo:IAO_0000115"
        },
        "description": {
            "description": "A free text description of the pattern.  Must be UTF-8 encoded.",
            "type": "string"
        },
        "disjointWith": {
            "$ref": "#/definitions/printf_owl_convenience"
        },
        "equivalentTo": {
            "$ref": "#/definitions/printf_owl_convenience"
        },
        "exact_synonym": {
            "$ref": "#/definitions/list_annotation_obo",
            "mapping": "oboInOwl:hasExactSynonym"
        },
        "generated_broad_synonyms": {
            "description": "An OBO convenience field to allow the specification of broad synonyms generated by interpolation of OWL entity names into printf text. Each entry may be annotated. \n",
            "items": {
                "$ref": "#/definitions/printf_annotation_obo",
                "mapping": "oboInOwl:hasBroadSynonym"
            },
            "type": "array"
        },
        "generated_narrow_synonyms": {
            "description": "An OBO convenience field to allow the specification of narrow synonyms generated by interpolation of OWL entity names into printf text. Each entry may be annotated. \n",
            "items": {
                "$ref": "#/definitions/printf_annotation_obo",
                "mapping": "oboInOwl:hasNarrowSynonym"
            },
            "type": "array"
        },
        "generated_related_synonyms": {
            "description": "An OBO convenience field to allow the specification of related synonyms generated by interpolation of OWL entity names into printf text. Each entry may be annotated. \n",
            "items": {
                "$ref": "#/definitions/printf_annotation_obo",
                "mapping": "oboInOwl:hasBroadSynonym"
            },
            "type": "array"
        },
        "generated_synonyms": {
            "description": "An OBO convenience field to allow the specification of exact synonyms generated by interpolation of OWL entity names into printf text. Each entry may be annotated. \n",
            "items": {
                "$ref": "#/definitions/printf_annotation_obo",
                "mapping": "oboInOwl:hasExactSynonym"
            },
            "type": "array"
        },
        "instance_graph": {
            "additionalProperties": false,
            "properties": {
                "edges": {
                    "items": {
                        "$ref": "#/definitions/opa"
                    },
                    "type": "array"
                },
                "nodes": {
                    "description": "Key = name of individual within this pattern doc Value = Type of individual specified using either  the quoted name of a class in the class dictionary of this pattern or a var name.  This field does not support typing via  anonymous class expressions\n",
                    "type": "object"
                }
            },
            "required": [
                "nodes",
                "edges"
            ],
            "type": "object"
        },
        "list_vars": {
            "description": "A dictionary of variables refering to lists of owl classes. Key = variable name, value = variable range of items in list specified as a valid OWL data-type.\n",
            "type": "object"
        },
        "logical_axioms": {
            "items": {
                "$ref": "#/definitions/printf_owl"
            },
            "type": "array"
        },
        "name": {
            "$ref": "#/definitions/printf_annotation_obo",
            "mapping": "rdfs:label"
        },
        "namespace": {
            "$ref": "#/definitions/printf_annotation_obo",
            "mapping": "oboInOwl:hasOBONamespace"
        },
        "narrow_synonym": {
            "$ref": "#/definitions/list_annotation_obo",
            "mapping": "oboInOwl:hasNarrowSynonym"
        },
        "objectProperties": {
            "description": "A dictionary of OWL object properties. key : label; value : short form id",
            "type": "object"
        },
        "pattern_name": {
            "description": "The name of the pattern.  This must be an ASCII string with no spaces. The only special characters allowed are '_' and '-'. By convention, this is used as the file name of the pattern - with an appropriate extension.\n",
            "type": "string"
        },
        "readable_identifiers": {
            "description": "A list of annotation properties used as naming fields, in order of preference.",
            "items": {
                "type": "string"
            },
            "type": "array"
        },
        "related_synonym": {
            "$ref": "#/definitions/list_annotation_obo",
            "mapping": "oboInOwl:hasRelatedSynonym"
        },
        "relations": {
            "description": "A dictionary of OWL object properties. key : label; value : short form id",
            "type": "object"
        },
        "subClassOf": {
            "$ref": "#/definitions/printf_owl_convenience"
        },
        "substitutions": {
            "items": {
                "$ref": "#/definitions/regex_sub"
            },
            "type": "array"
        },
        "vars": {
            "description": "A dictionary of variables ranging over OWL classes.   Key = variable name, value = variable range as manchester syntax string.\n",
            "type": "object"
        },
        "xref": {
            "$ref": "#/definitions/list_annotation_obo",
            "mapping": "oboInOwl:hasDbXref"
        }
    },
    "title": "DOSDP",
    "type": "object"
}

=== INCATools/dead_simple_owl_design_patterns/patterns/extrinsic_membrane_component.json
{
    "classes": {
        "extrinsic component of membrane": "GO_0019898", 
        "membrane": "GO_0016020", 
        "side of membrane": "GO_0098552"
    }, 
    "def": {
        "text": "The component of the %s consisting of gene products and protein complexes that are loosely bound to one of its surfaces, but not integrated into the hydrophobic region.", 
        "vars": [
            "membrane"
        ]
    }, 
    "equivalentTo": {
        "text": "'extrinsic component of membrane' and ('part of' some %s)", 
        "vars": [
            "membrane"
        ]
    }, 
    "name": {
        "text": "extrinsic component of %s", 
        "vars": [
            "membrane"
        ]
    }, 
    "pattern_name": "extrinsic_membrane_component", 
    "relations": {
        "part of": "BFO_0000050"
    }, 
    "vars": {
        "membrane": "'membrane' or 'side of membrane'"
    }
}

=== INCATools/dead_simple_owl_design_patterns/src/attic/patterns/anchored_membrane_component.json
{
    "classes": {
        "anchored component of membrane": "GO_0031225", 
        "membrane": "GO_0016020", 
        "side of membrane": "GO_0098552"
    }, 
    "def": {
        "text": "The component of the %s consisting of the gene products that are tethered to the membrane only by a covalently attached anchor, such as a lipid group that is embedded in the membrane. Gene products with peptide sequences that are embedded in the membrane are excluded from this grouping.", 
        "vars": [
            "membrane"
        ]
    }, 
    "equivalentTo": {
        "text": "'anchored component of membrane' and ('part of' some %s)", 
        "vars": [
            "membrane"
        ]
    }, 
    "name": {
        "text": "anchored component of %s", 
        "vars": [
            "membrane"
        ]
    }, 
    "pattern_name": "anchored_membrane_component", 
    "relations": {
        "part of": "BFO_0000050"
    }, 
    "vars": {
        "membrane": "'membrane' or 'side of membrane'"
    }
}

=== INCATools/dead_simple_owl_design_patterns/patterns/import_across_plasma_membrane.json
{
    "classes": {
        "chemical entity": "CHEBI_24431", 
        "cytosol": "GO_0005829", 
        "extracellular region": "GO_0005576", 
        "macromolecular complex": "GO_0043234", 
        "plasma membrane": "GO_0005886", 
        "transport": "GO_0006810"
    }, 
    "def": {
        "text": "The directed movement of %s from outside of a cell, across the plasma membrane and into the cytoplasmic compartment.", 
        "vars": [
            "imported"
        ]
    }, 
    "equivalentTo": {
        "text": "'transport' and ('has target start location' some 'extracellular region') and ('has target end location' some 'cytosol') and ('results in transport across' some 'plasma membrane') and ('imports' some %s)", 
        "vars": [
            "imported"
        ]
    }, 
    "name": {
        "text": "%s import across plasma membrane", 
        "vars": [
            "imported"
        ]
    }, 
    "pattern_name": "import_across_plasma_membrane", 
    "relations": {
        "has target end location": "RO_0002339", 
        "has target start location": "RO_0002338", 
        "imports": "RO_0002340", 
        "results in transport across": "RO_0002342"
    }, 
    "vars": {
        "imported": "'chemical entity' or 'macromolecular complex'"
    }
}

=== INCATools/dead_simple_owl_design_patterns/src/attic/patterns/bounding_membrane_of_organelle.json
{
    "classes": {
        "membrane-bounded organelle": "GO_0043227", 
        "whole membrane": "GO_0098805"
    }, 
    "def": {
        "text": "The lipid bilayer that forms the outer layer of a %s.", 
        "vars": [
            "organelle"
        ]
    }, 
    "equivalentTo": {
        "text": "'whole membrane' that ('bounding layer of' some %s)", 
        "vars": [
            "organelle"
        ]
    }, 
    "name": {
        "text": "%s membrane", 
        "vars": [
            "organelle"
        ]
    }, 
    "pattern_name": "bounding_membrane_of_organelle", 
    "relations": {
        "bounding layer of": "RO_0002007"
    }, 
    "vars": {
        "organelle": "'membrane-bounded organelle'"
    }
}

=== INCATools/dead_simple_owl_design_patterns/patterns/import_across_membrane.json
{
    "classes": {
        "cellular_component": "GO_0005575", 
        "chemical entity": "CHEBI_24431", 
        "macromolecular complex": "GO_0032991", 
        "membrane": "GO_0016020"
    }, 
    "def": {
        "text": "The directed import of some %s from %s, across the %s and into the %s.", 
        "vars": [
            "cargo", 
            "start", 
            "membrane", 
            "end"
        ]
    }, 
    "equivalentTo": {
        "text": "'transport' that and ('has target start location' some %s) and ('has target end location' some %s) and ('imports' some %s) and ('results in transport across' some %s)", 
        "vars": [
            "start", 
            "end", 
            "cargo", 
            "membrane"
        ]
    }, 
    "name": {
        "text": "%s import across %s", 
        "vars": [
            "cargo", 
            "membrane"
        ]
    }, 
    "pattern_name": "import_across_membrane", 
    "relations": {
        "has target end location": "RO_0002339", 
        "has target start location": "RO_0002338", 
        "imports": "RO_0002340", 
        "results in transport across": "RO_0002342", 
        "transports or maintains localization of": "RO_0002313"
    }, 
    "vars": {
        "cargo": "'chemical entity' or 'macromolecular complex'", 
        "end": "'cellular_compomnent'", 
        "membrane": "'membrane'", 
        "start": "'cellular_component'"
    }
}

=== INCATools/dead_simple_owl_design_patterns/patterns/expression_pattern.json
{
    "classes": {
        "cell": null, 
        "expression pattern": null
    }, 
    "def": {
        "text": "The sum total of all cells in a single organism in which expression of %s is occurring.", 
        "vars": [
            "expressed_feature"
        ]
    }, 
    "equivalentTo": {
        "text": "", 
        "vars": [
            "expressed_feature"
        ]
    }, 
    "name": {
        "text": "%s expression pattern", 
        "vars": [
            "expressed_feature"
        ]
    }, 
    "pattern_name": "expression_pattern", 
    "relations": {
        "has part": null, 
        "part of": "BFO_0000050"
    }, 
    "vars": {
        "expressed_feature": "'gene'"
    }
}

=== INCATools/dead_simple_owl_design_patterns/patterns/intrinsic_membrane_component.json
{
    "classes": {
        "integral component of membrane": "GO_0016021", 
        "intrinsic component of membrane": "GO_0031224", 
        "membrane": "GO_0016020", 
        "side of membrane": "GO_0098552"
    }, 
    "def": {
        "text": "The component of the %s consisting of gene products and protein complexes that have some covalently attached part (e.g. peptide sequence or GPI anchor), which spans or is embedded in one or both leaflets the membrane.", 
        "vars": [
            "membrane"
        ]
    }, 
    "equivalentTo": {
        "text": "'integral component of membrane' and ('part of' some %s)", 
        "vars": [
            "membrane"
        ]
    }, 
    "name": {
        "text": "intrinsic component of %s", 
        "vars": [
            "membrane"
        ]
    }, 
    "pattern_name": "intrinsic_membrane_component", 
    "relations": {
        "part of": "BFO_0000050"
    }, 
    "subClassOf": {
        "text": "'part of' some ('intrinsic component of membrane' and 'part of' some %s)", 
        "vars": [
            "membrane"
        ]
    }, 
    "vars": {
        "membrane": "'membrane' or 'side of membrane'"
    }
}
